openapi: 3.0.0
info:
  title: exo1 APi
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Serveur local

    paths:
    /ping:
      get:
        summery: recuperation de l'exo1
        reponse:
          '200':
            description: ok
            content:
              application/json:
                type: object
                properties:
                  message:
                    type: text/plan
                    exo1: "pong"






