openapi: 3.0.0

info:
  title: exo1 APi
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Serveur local
paths:
  /users :
    get:
      parametre:
        name :